"""Existing-software intake — read a project the team has already developed.

Where :mod:`intake` resolves *what new work* to do (a spec file or a prompt), this module
resolves *what software already exists* to do it against. It reads a previously generated
workspace into an :class:`ExistingProject`: the code/config files the team will carry
forward and modify, the documentation kept only for context, and a rendered ``brief`` that
grounds every phase of a feature run in what is already there.

This is the input side of the incremental ("feature") mode driven by
:func:`software_team.state.new_feature_state`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .skills.common import filesystem

# Files read for context only (regenerated by the doc phases), never seeded as editable
# source: everything under ``docs/`` plus the top-level README.
_DOC_PREFIX = "docs/"
_DOC_FILES = {"README.md"}

# Documentation surfaced in the grounding brief, most-useful first. Others are still
# preserved on disk; they are just left out of the prompt to keep it bounded.
_BRIEF_DOCS = (
    "README.md",
    "docs/product_backlog.md",
    "docs/architecture.md",
    "docs/test_plan.md",
)

# Per-document character budget in the brief, so a large doc cannot blow up a prompt.
_DOC_BUDGET = 1500


class ProjectError(ValueError):
    """The target workspace holds no software the team can extend."""


def _is_doc(rel_path: str) -> bool:
    """Return whether ``rel_path`` is documentation (context only, not editable source)."""
    return rel_path.startswith(_DOC_PREFIX) or rel_path in _DOC_FILES


@dataclass(frozen=True)
class ExistingProject:
    """A software project the team has already developed, loaded for an incremental run.

    Attributes:
        root: The workspace directory the project was read from.
        source_files: Code/config files (path -> content) to carry forward and modify.
        docs: Documentation files (path -> content) kept for context; regenerated by the
            doc phases rather than hand-edited.
    """

    root: str
    source_files: dict[str, str]
    docs: dict[str, str]

    @property
    def is_empty(self) -> bool:
        """Return whether the project has no source files to extend."""
        return not self.source_files

    @property
    def all_files(self) -> dict[str, str]:
        """Return every file (source + docs), e.g. to mirror the project elsewhere."""
        return {**self.docs, **self.source_files}

    def file_tree(self) -> str:
        """Return the sorted relative paths of every file, one per line."""
        return "\n".join(sorted(self.all_files))

    def brief(self) -> str:
        """Render the grounding digest of the existing software for a feature run.

        The digest is the project's file tree followed by a bounded excerpt of its key
        documents, under the :data:`software_team.state.FEATURE_BRIEF_HEADER` so a node
        (and the dry-run stub) can recognise feature mode.

        Returns:
            A markdown block describing the existing software.
        """
        # Imported here to avoid a circular import at module load (state imports nothing
        # from this module, but keeping the dependency lazy is cheap and clear).
        from .state import FEATURE_BRIEF_HEADER

        sections = [
            FEATURE_BRIEF_HEADER,
            "### Project files\n```\n" + self.file_tree() + "\n```",
        ]
        for name in _BRIEF_DOCS:
            content = self.docs.get(name, "").strip()
            if not content:
                continue
            if len(content) > _DOC_BUDGET:
                content = content[:_DOC_BUDGET].rstrip() + "\n… (truncated)"
            sections.append(f"### {name}\n{content}")
        return "\n\n".join(sections)


def load(root: str) -> ExistingProject:
    """Read the developed project at ``root`` into an :class:`ExistingProject`.

    Text files are partitioned into editable source and context-only docs; unreadable
    (e.g. binary) files are skipped so the loader is robust to whatever a workspace holds.

    Args:
        root: The workspace directory to read.

    Returns:
        The loaded project.

    Raises:
        ProjectError: If ``root`` does not exist or holds no extendable source files.
    """
    base = Path(root)
    if not base.is_dir():
        raise ProjectError(f"No project to extend: '{root}' is not a directory.")

    source_files: dict[str, str] = {}
    docs: dict[str, str] = {}
    for rel_path in filesystem.list_tree(root):
        try:
            content = filesystem.read_file(root, rel_path)
        except (UnicodeDecodeError, ValueError):
            continue  # skip binaries / anything outside the workspace
        (docs if _is_doc(rel_path) else source_files)[rel_path] = content

    project = ExistingProject(root=str(base), source_files=source_files, docs=docs)
    if project.is_empty:
        raise ProjectError(
            f"No source files found in '{root}'. Run `software-team run` to build a "
            "project first, then add features to it with `software-team feature`."
        )
    return project


def mirror(project: ExistingProject, output_dir: str) -> list[str]:
    """Copy every file of ``project`` into ``output_dir`` and return the paths written.

    Used when a feature run targets a fresh ``--out`` directory: the existing project is
    duplicated there first so the result is a complete, updated copy and the original is
    left untouched.

    Args:
        project: The loaded project to copy.
        output_dir: The destination workspace.

    Returns:
        The list of absolute paths written.
    """
    return filesystem.write_files(output_dir, project.all_files)
